env:
  browser: true
  es6: true
  jest: true
  node: true
extends: airbnb
globals:
  __DEV__: true
parser: babel-eslint
plugins:
  - babel
  - import
  - lodash
  - react
  - dependencies
root: true
rules:
  arrow-body-style: off
  arrow-parens: off
  class-methods-use-this: off
  comma-dangle:
    - warn
    - arrays: always-multiline
      exports: always-multiline
      functions: ignore
      imports: always-multiline
      objects: always-multiline
  consistent-return: off
  dependencies/no-cycles:
    - 1
    - skip:
        - table
  function-paren-newline: warn
  import/default: 2
  import/export: 2
  import/named: error
  import/newline-after-import: warn
  import/no-unresolved:
    - 2
    - amd: true
      commonjs: true
  import/prefer-default-export: off
  jsx-a11y/href-no-hash: off
  linebreak-style: off
  max-len:
    - warn
    - code: 160
  no-console:
    - warn
    - allow:
        - warn
        - error
        - time
        - timeEnd
  no-mixed-operators: off
  no-multi-assign: off
  no-param-reassign: off
  no-plusplus: off
  no-restricted-globals:
    - warn
    - self
    - find
    - this
    - postMessage
    - name
  no-trailing-spaces: 1
  no-underscore-dangle: off
  no-unused-expressions: 1
  no-unused-labels: 1
  no-unused-vars: 1
  prefer-const: 1
  prefer-destructuring: off
  quotes:
    - 1
    - single
  react/prop-types: 0
  semi:
    - 1
    - never
settings:
  import/extensions:
    - .js
    - .jsx
    - .json
  import/resolver:
    node:
      extensions:
        - .js
        - .jsx
        - .json
      moduleDirectory:
        - node_modules
        - .
