export plugBrowser from './browser'
export plugCookie from './cookie'
export plugKoaCookie from './koaCookie'
export plugSearchable, { search } from './searchable'
export plugLocalStorage from './localStorage'
